/**
 * Mock merchant records — 9 merchants covering High, Medium, and Low risk tiers.
 * Expected outcomes documented inline for Phase 2 verification.
 */
const MERCHANTS = [
  {
    id: "m001",
    name: "Urban Threads Co.",
    plan: "Pro",
    subscriptionStatus: "past_due",
    ordersLast30d: 42,
    ordersPrior30d: 48,
    daysSinceLastLogin: 5,
    daysSinceLastOrder: 3,
    activeProducts: 120,
    onboardingComplete: 100,
    supportTickets30d: 1,
    // Expected: High — past_due → Contact billing
  },
  {
    id: "m002",
    name: "Sunset Bakery",
    plan: "Starter",
    subscriptionStatus: "cancelled",
    ordersLast30d: 0,
    ordersPrior30d: 15,
    daysSinceLastLogin: 40,
    daysSinceLastOrder: 38,
    activeProducts: 0,
    onboardingComplete: 80,
    supportTickets30d: 0,
    // Expected: High — cancelled → Contact billing
  },
  {
    id: "m003",
    name: "Peak Outdoor Gear",
    plan: "Enterprise",
    subscriptionStatus: "active",
    ordersLast30d: 45,
    ordersPrior30d: 100,
    daysSinceLastLogin: 4,
    daysSinceLastOrder: 2,
    activeProducts: 340,
    onboardingComplete: 100,
    supportTickets30d: 0,
    // Expected: High — 55% order decline → Review catalog
  },
  {
    id: "m004",
    name: "Artisan Candle Studio",
    plan: "Pro",
    subscriptionStatus: "active",
    ordersLast30d: 30,
    ordersPrior30d: 32,
    daysSinceLastLogin: 25,
    daysSinceLastOrder: 5,
    activeProducts: 55,
    onboardingComplete: 100,
    supportTickets30d: 0,
    // Expected: High — no login 25 days → Re-engagement email
  },
  {
    id: "m005",
    name: "Green Leaf Organics",
    plan: "Pro",
    subscriptionStatus: "active",
    ordersLast30d: 2,
    ordersPrior30d: 20,
    daysSinceLastLogin: 6,
    daysSinceLastOrder: 45,
    activeProducts: 28,
    onboardingComplete: 100,
    supportTickets30d: 1,
    // Expected: High — no orders 45 days → Re-engagement outreach
  },
  {
    id: "m006",
    name: "Metro Fitness Supply",
    plan: "Pro",
    subscriptionStatus: "active",
    ordersLast30d: 60,
    ordersPrior30d: 80,
    daysSinceLastLogin: 3,
    daysSinceLastOrder: 1,
    activeProducts: 95,
    onboardingComplete: 100,
    supportTickets30d: 1,
    // Expected: Medium — 25% order decline → Review catalog
  },
  {
    id: "m007",
    name: "Craft Kids Toys",
    plan: "Starter",
    subscriptionStatus: "trial",
    ordersLast30d: 8,
    ordersPrior30d: 0,
    daysSinceLastLogin: 10,
    daysSinceLastOrder: 4,
    activeProducts: 12,
    onboardingComplete: 35,
    supportTickets30d: 0,
    // Expected: Medium — trial + low onboarding → Trial extension
  },
  {
    id: "m008",
    name: "Digital Print Hub",
    plan: "Pro",
    subscriptionStatus: "active",
    ordersLast30d: 55,
    ordersPrior30d: 52,
    daysSinceLastLogin: 2,
    daysSinceLastOrder: 1,
    activeProducts: 200,
    onboardingComplete: 100,
    supportTickets30d: 4,
    // Expected: Medium — 4 support tickets → Escalate to support
  },
  {
    id: "m009",
    name: "Bright Home Decor",
    plan: "Enterprise",
    subscriptionStatus: "active",
    ordersLast30d: 210,
    ordersPrior30d: 195,
    daysSinceLastLogin: 1,
    daysSinceLastOrder: 0,
    activeProducts: 480,
    onboardingComplete: 100,
    supportTickets30d: 0,
    // Expected: Low — stable/growing → Continue monitoring
  },
];
